### ISSUE TITLE
Negative scale on street view

### ISSUE THREAD

**Issue by lucaszb9** [benlikescode/geohub#25]
After a couple of games, Street View image is inverted now. Is this because of not paying the Google API?

![image](https://github.com/benlikescode/geohub/assets/77427075/082a9df1-c405-4507-ac80-b4504bfe7f1d)

**Comment by benlikescode** [comment]
Yes, in order to keep the game free... I have to set a daily quota for map loads or the costs would be way too high. 

There has been a lot of new traffic the past few days and so the daily quota is being reached very quickly. I am looking into other solutions to keep the game free but this is how it is for now. 

FYI: The daily quota resets around midnight Pacific Time (PT)
