### ISSUE TITLE
minimum accuracy to get a perfect score

### ISSUE THREAD

**Issue by Ely31** [benlikescode/geohub#37]
When playing a map that covers a small area such as a single city, if you are off by about 5m you still don't get a 5k on that round. In geoguessr, if you're within a reasonable distance of the spot you will get the full points. The way the scoring works now, it's basically impossible to get a perfect game on a small size map even if you get all the locations right.

**Comment by scottyboii** [comment]
I just played a round on Andorra, 5m away -> 4993. Definitely think the ratio needs adjusting a little.
![image](https://github.com/benlikescode/geohub/assets/32883419/9002ad4b-874e-447f-91c7-bbc802b46889)

**Comment by MaximilianEmel** [comment]
I don't think so; it raises the skill ceiling.

**Comment by scottyboii** [comment]
> I don't think so; it raises the skill ceiling.

There's raising the skill ceiling and being impossible, 5m is the difference between you clicking on the road and the "pin" being incorrectly off to the side. Even if you clicked exactly at the right address, the distance laterally from the middle of the road to the building the pin is incorrectly in would lose you your 5k. It is absolutely impossible to get it within 1m unless you're playing maps such as famous locations where you can memorise exactly where every location is.

**Comment by benlikescode** [comment]
I agree the scoring formula could likely be improved. @scottyboii what map were you playing in that screenshot you sent?

**Comment by scottyboii** [comment]
> I agree the scoring formula could likely be improved. @scottyboii what map were you playing in that screenshot you sent?

That was the Andorra map, just picked a random smaller country to test how precise you needed to be.

**Comment by benlikescode** [comment]
Gotcha, thanks!

**Comment by MapperTV** [comment]
Since Google Maps can be quite imprecise, a safe error distance is mandatory. Google itself removes Street View if the road is misplaced more than 20~25 meters. I would say any guess under 25m should give a perfect score. Also being able to edit this parameter for a custom map would be great so we don't need to artificially grow the map boundaries using the South Pole and the northern Canada trekker.

**Comment by benlikescode** [comment]
I agree with the under 25m always being a perfect score and letting you customize it for custom maps should be doable... but keep in mind that the scoring formula would still be influenced by the bounding NW and SE points, unless you have a better suggestion for that.

**Comment by MapperTV** [comment]
Maybe have two customizable parameters, one defining how many meters you need to guess under to have the perfect score and one that defines when above how much metetrs you will get 0 point, and the game will calculate the score between those two values.

So let's say someone wants to make a map with cities only and push players try to guess the correct city instead of randomly guess an area, they could set minimal distance to 100m and maximal distance to 10km, making any player making a random guess in a country lose all the points but rewarding the ones finding the city.

I do not know the formula so no idea how applicable this would be.

**Comment by benlikescode** [comment]
Just a small update that will always give 5k if within 25m.

Will keep those points in mind Mapper when I work on the map editor again
